server:
  port: 8761

eureka:
  instance:
    hostname: localhost #主机名
  client: #客户端的配置
    registerWithEureka: false #是否注册到Eureka中
    fetchRegistry: false #是否拉取注册列表
    serviceUrl: #Eureka服务端的地址 http://ip:端口/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版的Eureka